### ISSUE TITLE
Spamming system logs due to non-existent hwmon files

### ISSUE THREAD

**Issue by mgalgs** [paradoxxxzero/gnome-shell-system-monitor-applet#259]
I get this in my system log every 5 minutes:

```
Nov 25 11:02:14 mitchelh-linux gnome-session[814]: Gjs-Message: JS LOG: error reading: /sys/class/hwmon/hwmon1/fan1_input
```

This makes it very difficult to read my system logs.

I had a look at `check_sensors` but it looks like we're already bailing out if the files don't exist...   So I'm not sure where the problem is.

**Comment by Hecke** [comment]
me too...

though it is all 2-3 secs and freezes my system for a short time :-(

Jan 27 09:06:39 arenal gnome-session[1440]: Gjs-Message: JS LOG: error reading: /sys/class/hwmon/hwmon1/temp1_input

**Comment by najamelan** [comment]
I have the same problem

**Comment by darkxst** [comment]
this should been fixed by
https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/commit/d04c1366c53069b2e59b875a51878cf3a8d78b8a

**Comment by tommybutler** [comment]
I'm running Debian Jessie, and compiling from source isn't really feasible.  How, please tell me, how do I turn this off?  What process needs to be killed or whatever?  I can't just touch an empty file with that name into the sys filesystem to make the complaint go away... Please, seriously please tell me how to make it stop.  Bandaids and duct tape fixes are perfectly acceptable for me.

**Comment by p91paul** [comment]
@tommybutler There is no "compiling from source" involved, javascript extensions are interpreted without needing to be compiled and are installed to your home folder, so you don't need administrative permissions. You just have to click on the "Download ZIP" button in the homepage of this project, unzip the file, and copy the extracted system-monitor@paradoxxx.zero.gmail.com folder in /home/<your user>/.local/share/gnome-shell/extensions/, replacing files if you have the extensions.gnome.org version installed. Please remember that .local is an hidden folder, so if you are using your file manager you'll have to set hidden files and folders to be visible to see it.

Anyway, detailed manual install instructions (slightly different from the ones I am providing here, mainly because they require installing git) are also provided on the project homepage.

**Comment by tommybutler** [comment]
Thank you @p91paul as I was unaware these extensions were javascript code.  I appreciate the tip, it got me fixed right up and now my syslog isn't bloating out anymore.  Thanks again!

**Comment by tommybutler** [comment]
Update: this git zip version successfully eliminated the problem on my tower workstation yesterday.  Just now I downloaded it on my laptop (an IBM Lenovo T410) and the problem persists.  Exactly every 5 seconds the extension peppers my syslog with:

.Jun  3 01:52:54 donut gnome-session[2649]: Gjs-Message: JS LOG: error reading: /sys/class/hwmon/hwmon2/device/fan1_input

This is my favorite gnome-shell extension _by far_ and I look forward to a fix soon.  If I have time I'll look through the code for anything that specifically tries to read hwmon2 fan data.  Please let me know if there's anything I can do to help move toward a solution.

**Comment by p91paul** [comment]
Yeah, seems like @darkxst fixed it for temperature, but not for fan. Possibly the same applies to other sensors as well?

**Comment by harrim4n** [comment]
Having the same issue with /sys/class/hwmon/hwmon1/device/fan1_input under arch.

**Comment by salderma** [comment]
This issue still persists on RHEL7 variants running Gnome 3.8.  I've had this machine for about 3 months, running Scientific Linux 7.1.  I had installed from the git repo and had to rewind to cc86a28, which seems to be the most latest commit which works for Gnome 3.8.  This issue appears in all commits that 3.8 works with from 6aac0f3...cc86a28.

The extension does not seem to work at all with commit 452ffc5 as noted in the commit comments.

Is there anyway to patch this to work with the EL7 linux variants?

**Comment by salderma** [comment]
I have a branch for Gnome 3.8, which fixes this logging problem.  If @darkxst can pull my entire gnome-3.8 branch over (like his gnome-3.0 and gnome-3.2 branches) that would add some nice support for the EL7 folks using gnome-shell, and loving this extension.

https://github.com/salderma/gnome-shell-system-monitor-applet/tree/gnome-3.8

**Comment by salderma** [comment]
I have a branch for Gnome 3.8, which fixes this logging problem. If @darkxst can pull my entire gnome-3.8 branch over (like his gnome-3.0 and gnome-3.2 branches) that would add some nice support for the EL7 folks using gnome-shell, and loving this extension.

https://github.com/salderma/gnome-shell-system-monitor-applet/tree/gnome-3.8

This branch picks up after cc86a28 with the logging fix as my contribution.

**Comment by lgpasquale** [comment]
I believe salderma's branch should probably be merged into master, or these error messages should be disabled some other way.
